export const postsTagsOptions = [
  { key: "TravelTips", label: "TravelTips" },
  { key: "DestinationGuides", label: "DestinationGuides" },
  { key: "TravelInspiration", label: "TravelInspiration" },
  { key: "TravelNews", label: "TravelNews" },
  { key: "TravelDeals", label: "TravelDeals" },
  { key: "BeachDestinations", label: "BeachDestinations" },
  { key: "AdventureTravel", label: "AdventureTravel" },
  { key: "HiddenGems", label: "HiddenGems" },
  { key: "EcoTourism", label: "EcoTourism" },
  { key: "CulturalExperiences", label: "CulturalExperiences" },
  { key: "FamilyTravel", label: "FamilyTravel" },
  { key: "LocalCuisine", label: "LocalCuisine" },
];
export const postCategoryOptions = [
  { key: "Adventure", label: "Adventure" },
  { key: "Culture", label: "Culture" },
  { key: "Food", label: "Food" },
  { key: "Nature", label: "Nature" },
  { key: "Beach", label: "Beach" },
  { key: "City", label: "City" },
  { key: "Wellness", label: "Wellness" },
  { key: "History", label: "History" },
  { key: "Family", label: "Family" },
  { key: "Luxury", label: "Luxury" },
  { key: "Backpacking", label: "Backpacking" },
  { key: "RoadTrips", label: "RoadTrips" },
];
